spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.com.example.backend=INFO

jwt.secret=${JWT_SECRET}

file.upload-dir=uploads/
file.base-url=${APP_BASE_URL}/images/

server.port=${PORT:8080}