spring.application.name=backend

spring.datasource.url=jdbc:mysql://kodama.proxy.rlwy.net:36035/app_appertal?connectTimeout=5000
spring.datasource.username=root
spring.datasource.password=ziMfZaRGXsXDUmUOjjUjBunYVbvokBEl

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.example.backend=TRACE
logging.level.org.springframework.security=DEBUG

jwt.secret=${JWT_SECRET}

# Upload folder
file.upload-dir=uploads/

# Public URL
file.base-url=https://appartel-backend.onrender.com/images/

server.port=${PORT:8080}